CHANGELOG.md, maestral/cli.py, maestral/daemon.py, setup.py
Migrate from lockfile to fasteners which use POSIX fcntl locks. This has the following advantages:
- Locks are always released when the process quits, even on segfaults.
- PID of locking process can be retrieved from kernel instead of reading from lockfile.
- No race conditions on startup or quit.
=> Migrate daemon locks from lock file to fcntl

CHANGELOG.md, maestral/cli.py, maestral/client.py, maestral/config/main.py, maestral/main.py, maestral/oauth.py, tests/test_main.py, tests/test_sync.py
Dropbox recently introduced short-lived oauth tokens to replace the previously long-lived tokens and will deprecate the old auth tokens in mid 2021. This PR introduces support in Maestral for short-lived tokens which are always used to link new accounts. Previously linked accounts will continue to use long-lived tokens until a future update.
=> Use short-lived oauth tokens

maestral/daemon.py, maestral/main.py
Use asyncio to run the daemon's event loop. This has several advantages:
* We can use asyncio to handle dbus signals. This allows us to have clickable notifications on Linux with the DBus backend.
* We can integrate asyncio with the macOS `CFRunLoop`, allowing us to have clickable notifications on macOS where clicks are dispatched back to our run loop.
* We can use async calls for lightweight periodic tasks such as update checks and watchdog notifications.
This is in preparation for #101.
=> Pyro5 asyncio integration

maestral/daemon.py, maestral/errors.py, maestral/main.py, maestral/sync.py, maestral/utils/notify.py, maestral/utils/notify_base.py, maestral/utils/path.py, setup.py, tests/test_main.py, tests/test_sync.py
Keep the revision index in our SQlite database and store addition information for every path in the index:
* The unique Dropbox ID
* The `last_sync` time for the last upload sync.
* The content hash (not yet used)
* The item type (file vs folder)
Other changes are:
* Optimise how we determine the correct casing of a path: Dropbox only provides correct casing for the basename and not any parent directories in `path_display`. We previously use the casing of any existing local folders for parent directories. This has been now changed to use the casing of basenames from previous sync events, if available, or from existing entries in our local index. If neither can be used, the Dropbox server is queries explicitly for the metadata of all parent directories.
* Rename a local file or folder if …
=> Keep rev index in SQLite database

tests/test_main.py, tests/test_sync.py
This PR updates all sync tests to set up a fresh configuration / link to Dropbox before the test instead of using a common configuration for all tests.
Advantages:
* Tests are fully independent and a single failure won't spill over to other tests. This makes it much easier to find issues.
Disadvantages:
* Sync tests take even longer
* Possible issues from interactions between sync tests may not be noticed. However, this was never the intention in the first place.
=> Use fresh link for each sync test

.github/workflows/docker.yml, .github/workflows/dockerhub-repo-description.yml, Dockerfile, README.md
This PR contains the following:
- Dockerfile that creates a minimal image of 36MB (based on python:3.8-alpine).
- Github Action workflow, that builds, caches, pushes the image to Docker Hub.
- A 2nd Github Action job that pushes the content of the README.md as the description to the Docker Hub repo. This happens on newly tagged release.
- The build creates Docker image for amd64, arm/v7 (32bit) and arm64 (aka arm/v8) architectures, so you can use it on your Raspberry Pi, OSMC box, Synology NAS, etc.
- https://hub.docker.com/r/aries1980/maestral/tags
- https://github.com/aries1980/maestral/runs/1203608714?check_suite_focus=true
- https://github.com/aries1980/maestral/runs/1203483095?check_suite_focus=true (For the repo description update)
- https://hub.docker.com/r/aries1980/maestral (For …
=> ISSUE-187: Docker image for headless service

.github/workflows/test.yml, tests/test_main.py, tests/test_sync.py
This PR is to enable running sync tests with a linked Dropbox account on external PRs.
* Run Github action in `pull_request_target` to allow access to secrets.
* Create short lived access token in GitHub action to pass to possibly malicious PR.
* Don't run sync and API tests if no Dropbox token is available.
=> GitHub action tests on PR

CHANGELOG.md, maestral/client.py, maestral/daemon.py, maestral/main.py, maestral/sync.py, maestral/utils/__init__.py
This PR reduces the memory usage during an initial download and when syncing remote changes if the number of items to sync exceeds 5000. See issue #205.
=> Reduce memory usage on initial sync

src/maestral/utils/autostart.py
This PR simplifies the autostart module by removing all support for GUIs and frozen applications. The reasoning is:
* Providing a "start-on-login" option for a GUI fundamentally is the job of the GUI itself. Removing this from the `maestral` module results in a clearer separation of responsibilities. As a tradeoff, there may be some code-duplication in the GUI, depending on its autostart mechanism and if it aims to be cross-platform.
* We will move away from PyInstaller to briefcase for bundling. The latter provides an almost unmodified Python runtime and pip-installed Python packages, reducing the need to specially accommodate "frozen" executables.
The autostart module itself is still retained for the CLI which is bundled together with the daemon instead of a separate package.
This PR …
=> Refactor autostart

src/maestral/sync.py, src/maestral/utils/caches.py
Instead of keeping a bare dictionary as cache for past case conversions and manually clearing it, this PR uses a (very simple) least-recently-used (LRU) cache which keeps the last 5,000 case conversions in memory.
=> Optimise case conversion cache

src/maestral/cli.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/notify.py
* Separate manual desktop notifier and logging handler into different classes.
* Keep the desktop notification logging handler always on level ERROR.
* Emit all other notifications (file changes, sync issues, etc) explicitly and not indirectly through logger. This reduces unintentional / hidden side effects of log messages.
* Remove the CLI option to completely disable desktop notifications. Error messages will now always trigger a notification.
=> Refactor notifications

CHANGELOG.md, src/maestral/daemon.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/networkstate.py, src/maestral/utils/networkstate_base.py, src/maestral/utils/networkstate_linux.py, src/maestral/utils/networkstate_macos.py, src/maestral/utils/notify.py, src/maestral/utils/notify_linux.py
This PR refactors threading and minimises tasks that require frequent polling. As a result, the daemon now comes very close to 0% CPU usage when idle. Changes are:
* Checking for network connection has now been moved to a separate module `.utils.networkstate` which subscribes to updates from the operating system on network status changes:
1. On macOS, this uses `SCNetworkReachability` from the `System Configuration` framework which directly checks for the reachability of a host (www.dropbox.com in our case) and runs a callback when its reachability changes. This requires a running `CFRunLoop` which is already set up by the daemon by default.
2. On Linux, this attempts to use the Dbus service `org.freedesktop.NetworkManager`. This requires a running asyncio event loop which is already set …
=> Reduce idle cpu polling

src/maestral/sync.py, tests/linked/fixtures.py, tests/linked/test_sync.py
This PR fixes errors in conflict resolution which were introduced in #221. Those occur because a download sync is no longer always followed by an upload sync and the local cursor is therefore no longer incremented after every download sync. We can therefore no longer compare a file's ctime to the local cursor to check for conflicts. Instead, a new API `SyncEngine.has_unsynced_changes` is introduced which recurses over the subtree from the given path and compares it to our index.
Two related errors are also fixed:
1.  An issue where remote deleted events where incorrectly classified, leading to some deletions being incorrectly applied after other sync events. This did not lead to any known issues.
2. An issue where remote deletions and folder creations where applied in the order provided …
=> Fix conflict resolution

src/maestral/cli.py, src/maestral/utils/cli.py
This PR moves the code for printing formatted tables and grids to a new utils module `utils.cli`. It also adds some color and style to terminal output.
=> Move code for printing tables and grids to cli to separate module

CHANGELOG.md, src/maestral/main.py, tests/linked/test_main.py
* Allow setting `Maestral.excluded_items` directly
* Allow including items that lie within excluded folders through `Maestral.include_item()`
* Deprecate `Maestral.set_excluded_items()`
=> Selective sync updates

src/maestral/database.py, src/maestral/fsevents/__init__.py, src/maestral/logging.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/__init__.py, src/maestral/utils/serializer.py, tests/linked/test_sync.py
This PR fixes #230 by enabling proper handling of Python surrogate escapes throughout the `sync` module.
#230 arrises in the first place because paths in Unix are bytes while Python handles all paths as strings. Normally, the platform will report a file system encoding with `sys.getfilesystemencoding` which is used by Python to decode byte paths to strings. However, the OS APIs never actually enforce this encoding. It is therefore possible to receive bytes with a different encoding which Python will replace with "surrogate escapes" in the string (see the [docs](https://docs.python.org/3/library/os.html#os.fsdecode) and an excellent writeup of the problem by [beets](https://beets.io/blog/paths.html)).
Working with such strings can be difficult. Printing them to the console (or to our logs) …
=> Fix file path decoding on problematic bytes

src/maestral/sync.py, tests/linked/test_sync.py
Fixes #243 by creating fake `DeletedMetadata` when we cannot locate remote Metadata (existing or deleted) for a path in our pending downloads.
=> Fix inavlid path in pending downloads

CHANGELOG.md, src/maestral/sync.py
This PR uses a custom `listdir` function in `DirectorySnapshot` to take into account the `mignore` rules.
Using this PR, there is no need to snapshot ignored folders which can save considerable time and memory.
Fixes #216
Note: there are no new features, just performance improvements
=> Use mignore when creating directorysnapshot

CHANGELOG.md, setup.py, src/maestral/main.py, src/maestral/oauth.py
Keyring v22.0 has renamed the macOS backend from `keyring.backends.OS_X` to `keyring.backends.macOS`.
This PR bumps keyring to >=22.0, adapts imports, and migrates relevant config values.
=> Update keyring requirement to >= 22

CHANGELOG.md, src/maestral/client.py, src/maestral/main.py, src/maestral/sync.py, tests/linked/conftest.py, tests/linked/test_sync.py, tests/offline/test_ignoring_events.py
This PR refactors the initial indexing and subsequent `/files/list_folder/continue` calls to be resumable, i.e., to work with an intermediate curser during an indexing job.
This means that we must always start by indexing the entire Dropbox to work with global cursers instead of skipping excluded folders and therefore may incur a performance tradeoff in case of a large number of excluded items. However, this results results in more robust behaviour for very large Dropbox folders when restarting an indexing job after a lost connection or a restart.
See #289, #186 and #138.
=> Resumable indexing

CHANGELOG.md, src/maestral/cli.py, src/maestral/client.py, src/maestral/errors.py, src/maestral/main.py, tests/linked/conftest.py, tests/linked/test_main.py
This PR introduces support to create and manage shared links.
1. Adds methods to the client API: `create_shared_link`, `revoke_shared_link` and `list_shared_links`.
2. Adds methods to the public API: `create_shared_link`, `revoke_shared_link` and `list_shared_links`.
3. Add CLI command group `sharelink` with the following commands:
* `sharelink create DROPBOX_PATH --password='secret' --expires='2022-12-18 20:50'`: Creates a new shared link, optionally with password and expiry time. The last two options are not supported on basic accounts.
* `sharelink revoke URL`: Revokes the given link.
* `sharelink list [DROPBOX_PATH]`: List all shared links for a path or the entire Dropbox.
Closes #213.
=> Shared link api

CHANGELOG.md, src/maestral/cli.py, tests/linked/test_cli.py, tests/offline/test_cli.py
This PR reduces the number of CLI commands by introducing new command groups and removing rarely used commands (such as `maestral restart`). In particular:
* Moves linking and unlinking to a new command group `maestral auth` with subcommands `link`, `unlink` and `status`.
* Removes the `maestral restart` command. Use `stop` and `start` instead.
* Removes the `maestral account-info` command. Use `maestral auth status` instead.
=> Simplify CLI

CHANGELOG.md, src/maestral/main.py, src/maestral/utils/integration.py
This PR will prevent any periodic (typically weekly) reindexing if the device is not connected to AC power. This will prevent draining the battery due to CPU heavy hashing for file content.
=> Only trigger periodic indexing if we have AC power

CHANGELOG.md, src/maestral/client.py, src/maestral/daemon.py, src/maestral/sync.py, src/maestral/utils/integration.py, tests/linked/test_main.py
Following the discussion in #305, this PR improves the error message when the user is running out of inotify watches or instances:
1. Recommend default values of `max_user_watches = 524288` and `max_user_instances = 1024` if the current limits are lower. Otherwise, recommend to double the current values. There is no good way to predict how many watches will be needed since we do not know what other programs are using (unless they are currently running) or might be using in the future.
2. Recommend to apply the new settings with `sysctl -p` instead of rebooting.
This error message is generated and handled by the daemon and therefore should remain as brief as possible. Handling by the GUI can be more verbose and may in the future offer to adjust inotify settings on behalf of the user.
=> Improve inotify error message

CHANGELOG.md, docs/background/config_files.rst, src/maestral/cli.py, src/maestral/config/main.py, src/maestral/config/user.py, src/maestral/sync.py
This PR introduces the ability to have one-way syncing only, for instance only download syncs. This can be useful if the user just wants to mirror a remote Dropbox or has a local file system which does generate events for file changes (for instance some distributed file systems which have inotify disabled for good reasons).
Note that conflict resolution remain unaffected. For instance, when an unsynced local change would be overwritten by a remote change, the local file will be still moved to a "conflicting copy". However, the conflicting copy will not be uploaded.
Together with the above change, a new CLI command group `maestral config` has been introduced with subcommands `get` and `set`. It provides direct access to config values. For example:
```
maestral config set max_cpu_percent 50 …
```
=> One way sync and config access

CHANGELOG.md, src/maestral/errors.py, src/maestral/sync.py
This PR fixes a problem where the download of a folder newly included by selective sync would never complete under two circumstances:
1. If syncing is manually paused by the user during the download.
2. If the connection to Dropbox is lost and the download thread is externally stopped as a result.
In both circumstances, there was no error raised in the download thread itself and the `pending_download` entry was cleared when `get_remote_item` returned without an error. The fix now ensures that the download thread is always aborted when externally stopped.
In addition, this PR changes the way we handle connection issues. If the low-latency check shows connection issues, we update the status reported by the public API to `connected = False` but do not force the sync threads to abort. …
=> Fix download interrupted by connection problems

src/maestral/cli.py, src/maestral/constants.py, src/maestral/main.py, src/maestral/sync.py, tests/linked/test_cli.py
This PR fixes an issue where the daemon would restart syncing when an internet connection is established despite being paused.
This PR also cleans up some status messages left over from the old API where it was possible to either pause or stop the daemon.
=> Fix resuming sync after paused while disconnected

tests/linked/test_sync.py
This PR adds tests for unusual unicode characters, including those which may be normalised by some file system APIs (such as é on HSF+).
=> Add tests for exotic unicode characters

src/maestral/client.py, src/maestral/main.py, src/maestral/sync.py
This PR introduces manual scoping of network sessions.
This is used to create a new network session and clean up its resources for:
1. Individual upload or download threads from our thread pool.
2. Entire upload or download sync cycles.
3. Main API calls that may use significant network resources.
This improves memory usage for long running daemons by more frequently and immediately cleaning up network resources. It may also work around a memory issue with `requests` when used in threads, see https://github.com/psf/requests/issues/4601#issuecomment-603326738.
=> Improve resource management for network sessions

src/maestral/sync.py, tests/offline/test_cleaning_events.py
Fixes #337 by rescanning a local path if the reported file system events are ambiguous.
=> Fix upload sync of modified MS Office files on macOS

setup.py, src/maestral/database.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/orm.py
This PR switches from using sqlalchemy for database access to our own ORM layer which is a lot more basic. This has a few advantages:
1. Reduced baseline memory usage: the sqlalchemy module requires about 10 MB of memory while our own ORM only requires 0.5 MB.
2. Reduced peak memory usage: Our own index entry object requires about 50% less memory. This reduces the peak memory usage during indexing, especially when starting up the sync.
3. Increased performance: More complex database operations are handled by explicitly writing the SQL statements, resulting in less overhead to generate statements.
See #205 and #248.
=> Switch from sqlalchemy to our own ORM

src/maestral/autostart.py, src/maestral/constants.py, src/maestral/daemon.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py, src/maestral/utils/orm.py, src/maestral/utils/path.py, tests/linked/test_sync.py
This PR introduces a new local indexing algorithm which minimises memory usage by loading local file paths iteratively and freeing them immediately after use. This is similar to what was already done for loading index database entries in case of Dropbox with > 200,000 items.
The performance hit due to reduced caching has been mitigated with improvements to the ORM layer.
The reduced peak memory usage during indexing also has the advantage that pymalloc can do a more efficient job and we have less memory fragmentation over the lifetime of the process.
=> Optimise local indexing

src/maestral/cli.py, src/maestral/client.py, src/maestral/config/main.py, src/maestral/daemon.py, src/maestral/logging.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/oauth.py, src/maestral/sync.py, src/maestral/utils/integration.py, tests/linked/conftest.py, tests/linked/test_main.py, tests/offline/conftest.py, tests/offline/test_cli.py
This PR scopes loggers by config name instead of using global loggers. This prevents interference when running different Maestral instances in the same process.
It also initialises logging early during the daemon startup so that startup logs will now be properly written to the log file and journal.
=> Scope loggers by config name

codecov.yml, src/maestral/client.py, src/maestral/daemon.py, src/maestral/database.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/test_sync.py
This PR improves exception handling during upload sync:
* Permission errors and other unexpected OSErrors during startup indexing are no longer ignored but result in hard failures. This prevents remote items from being deleted if they cannot be indexed locally due to permission errors etc.
* Simplifies some error handling code.
* Don't raise errors when we cannot create cache dir during init.
* Adds tests for a wider variety of local OSErrors.
=> Improve exception handling during upload sync

.github/ISSUE_TEMPLATE/bug_report.md
The python pip package PyQt5 has no __version__ attribute (unlike most of the other ones who does).
The solution I found to find the PyQt5 package version is this.
Update the bug report template to clarify how to find PyQt5 package version
=> Clarify how to find PyQt5 version

CHANGELOG.md, setup.py, src/maestral/cli.py, src/maestral/config/main.py
=> Support for shell completion

src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py
* Return file status for root folder instead of just unwatched (fixes #389).
* Determine file status recursively for folders: if any of the containing files is being synced, this is now reflected in the file status for the parent folders.
=> Improvements to filestatus API

src/maestral/sync.py
This PR improves the performance of managing local event ignores.
1. Ignores are stored in a set instead of a list.
2. Expired ignores are only pruned after a completed sync cycle instead of when exiting the `FSEvents.ignore` context. The increase in memory usage should be small since only recursive ignores are kept after the corresponding event was recorded.
=> Performance improvement to ignores

src/maestral/daemon.py, tests/offline/test_daemon.py
fasteners 0.16.1 has a couple of API changes which we need to adapt to:
1. It no longer tracks if our own process acquired the lock. We need this information to determine the PID of the locking process (only if we are the locking process) and therefore track this ourselves now.
2. It no longer raises a `RuntimeError` when trying to release a lock which another process acquired and which we therefore cannot release. We raise this error ourselves now.
=> Update interprocess lock for fasteners 0.16.1

CHANGELOG.md, src/maestral/sync.py, tests/linked/test_sync.py
This PR closes #395 by fixing typos in the type hints.
It also improved typing for the `client` argument of various `SyncEngine` methods and ensures that the correct client instance is used when renaming local conflicts.
=> Fix type hints for client instance

src/maestral/sync.py
This PR fixes #413.
`SyncEngine.is_excluded()` is called most of the time with paths that start with a leading "/", either absolute paths on the local drive or "absolute" paths with respect to the Dropbox root. However, it may occasionally be called with file names without a leading "/", in particular when getting the ctime of a local folder:
https://github.com/SamSchott/maestral/blob/d149f8074f9effa9797c401feedf4a291056b332/src/maestral/sync.py#L3148-L3158
This would previously lead to an index error when getting the directory name.
=> Fix IndexError when passing a relative path to `is_excluded`

src/maestral/cli.py, src/maestral/config/base.py, src/maestral/config/main.py, src/maestral/config/user.py, tests/offline/config/conftest.py, tests/offline/config/test_user.py
This PR simplifies the config module as follows:
* Config version parsing and tracking is handled entirely by `packaging.version.Version`. Previous parsing methods have been removed.
* Exception handling for writing config files has been simplified.
* Error handling in `UserConfig.cleanup()` has been improved.
* More granular tests for getting, setting and creating config options.
* Added missing parameters to doc strings and converted all doc strings to rest syntax.
=> Refactor config module

src/maestral/config/main.py, src/maestral/config/user.py, src/maestral/main.py, src/maestral/oauth.py, src/maestral/sync.py, tests/offline/config/conftest.py, tests/offline/config/test_user.py, tests/offline/utils/test_appdirs.py
This PR reorganises the sections of the config and state files as follows:
1. Config file:
* `account_id` and `keyring` moved to `auth` section
* `path` and `excluded_items` moved to `sync` section
2. State file:
* `token_access_type` moved to `auth` section
=> Migrate config and state keys

setup.py, src/maestral/daemon.py, src/maestral/main.py
This PR simplifies the way we shut down the daemon. Instead of calling `Maestral.shutdown_daemon()` directly via Pyro5, we send SIGTERM to the daemon process and rely on the signal handler to invoke `Maestral.shutdown_daemon()`.
This has the advantage that, if the daemon process has become completely unresponsive, the remote `Maestral.shutdown_daemon()` call would block while sending SIGTERM will just fail to stop the process and can be followed up by SIGKILL after a timeout.
This change means that we need to know the daemon's PID. This is currently obtained by finding the process which has a write lock on the lock file, using ctypes calls which may fail on the some platforms. In this case, `maestral stop` will report "failed" and the user must manually stop the process.
This PR also …
=> Daemon shutdown improvements

CHANGELOG.md, src/maestral/client.py, tests/linked/test_client.py
Fixes #432 by correctly reading any error status codes from the HTTP response (instead of the request itself).
=> Fix handling of http errors

src/maestral/sync.py
This PR improved error handling when creating temporary files for downloads:
1. If we cannot create a temporary file because the cache dir cannot be found, call `SyncEngine.ensure_dropbox_folder_present()`.
2. Retry creation of temp file up to 10 times.
3. Reduce number of retries for creation of cache dir from 100 to 10 times.
=> Optimise temp file creation

CHANGELOG.md, src/maestral/utils/integration.py
I guess this is an edge case, but I was trying to run maestral's cli on a server where connections are only possible through a proxy. The Python SDK from Dropbox uses the `requests` python package which handles environment variables like `http_proxy` or similar accordingly.
Maestral's `check_connection` function uses sockets to establish a connection with `dropbox.com` over Port 80 which was not possible on my machine. This PR uses a `HEAD` request (which uses the `*_proxy` environment variables) if `http_proxy` is set and uses the existing socket method otherwise.
=> Perform connection check using head request if http_proxy ist set

CHANGELOG.md, setup.py, src/maestral/sync.py, tests/offline/test_cleaning_events.py
This PR improves cleaning local file events:
1. We reduce the number of iterations over all file events by a factor of 3, therefore speeding up event cleanup by 3x.
2. We preserve the order of events during cleanup.
3. We upload local changes in order of folder hierarchy and sorted by occurrence within each level.
The last two changes fix an issue when interrupting / pausing during an upload sync: If items are not synced in-order, a remote item `folder/subfolder/item` could be synced before `folder/subfolder`, therefore creating the remove item `folder/subfolder` as a side-effect without creating an entry for it in our local index. This is typically not a problem unless the sync is aborted before we actually process `folder/subfolder`. In this case, we have "uploaded" a remote item …
=> Improve cleaning local events

CHANGELOG.md, src/maestral/client.py
This PR improves handling of exotic OSErrors such as device or file system related errors. Instead of raising an unexpected error, a sync issue is created if the error relates to a specific sync event. This will allow other sync jobs to continue while informing the user of the specific file where the error was encountered.
Fixes #437.
=> Improve handling of exotic OSErrors

README.md
The CLI documentation link redirects to https://maestral.app/cli/ (with an ending slash), which gives a "page not found" error. https://maestral.app/cli works. It could probably be also solved by modifying the redirection.
=> CLI documentation link update

.github/workflows/test.yml, CHANGELOG.md, src/maestral/client.py, src/maestral/config/main.py, src/maestral/database.py, src/maestral/errors.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py, tests/linked/conftest.py, tests/linked/test_cli.py, tests/offline/conftest.py, tests/offline/test_client.py, tests/offline/test_manager.py
This PR fixes #441. In particular:
1. The root namespace of the user will always be used for syncing. If the root namespace is a team namespace, top level shared folders will be synced if the user has access to them.
2. We gracefully handle when a user joins or leaves a team or switches teams. When joining a team, this is currently done by moving all local "user" files to `Dropbox/User Name` and downloading shared folders to `Dropbox/`. This is reversed when leaving a team. Folders excluded by selective sync are preserved during this migration. Changing team membership will currently trigger a full reindexing but no new download of existing user files.
See https://developers.dropbox.com/dbx-team-files-guide for information on Dropbox Team Spaces.
=> Include full team namespace in sync

src/maestral/daemon.py, tests/linked/conftest.py, tests/linked/test_cli.py, tests/offline/test_cli.py, tests/offline/test_daemon.py
* Tweak timeouts for daemon startup.
* Release lock explicitly before daemon exit.
* Don't rerun flaky tests.
=> Daemon startup improvements

tests/linked/conftest.py, tests/linked/test_sync.py
This PR speeds up tests by checking for an idle daemon by counting the number of successful sync lock acquisitions.
=> Speed up tests

CHANGELOG.md, src/maestral/utils/cli.py
Fixes an issue where output of CLI commands would be truncated to 80 chars when not attached to an interactive stream. Fixes #505.
=> Fix maximum line width for CLI output

CHANGELOG.md, src/maestral/client.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/test_sync.py, tests/offline/test_cli.py
This PR improves the handling of some OSErrors:
1. Improves handling of OSErrors when determining the ctime of local files. Fixes #506.
2. Improve error messages when file names or paths are too long.
3. Only recursively clear errors when a successful deletion or move occurs.
=> Improve OSError handling

src/maestral/daemon.py
This PR moves acquiring the daemon lock of try-except block. This prevents us from releasing the daemon lock in the `finally` clause of the block even when we did not acquire the lock. Fixes #519.
=> Move process management outside of try-except block

src/maestral/oauth.py
Some exceptions when accessing the system keyring are not caught and reraised as `keyring.errors.KeyringError`. This includes DBus timeouts, as reported in #558.
This PR catches all exceptions when accessing the system keyring and reraises them as `maestral.errors.KeyringAccessError`. This results in proper propagation to and handling by frontends such as the CLI or GUI.
This PR also fixes a bug where deleting the credentials would not reset the preferred keyring, despite setting the `keyring` config value to "automatic". They preferred keyring would only be reset for new `OAuth2Session` instances.
=> Improve keyring error handling

src/maestral/database.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/orm.py
Maestral saves content hashes of local files in a SQLite database table. This acts as a cache to avoid repeatedly calculating content hashes of the same file if it has not been modified. To avoid returning outdated hashes, the mtime is stored together with the hash and compared against the current mtime of the file. If the mtime is different, the hash is recalculated.
The primary key for the table currently is the local file path. This can lead to incorrect hashes being returned from the cache if a local file was replaced by another file with the same mtime.
This PR uses the inode as the primary key instead and still checks for equal mtimes. This guards both against different files with the same mtime and different files with the same inode (inode recycling).
The local path is still …
=> Inode-based hash cache

CHANGELOG.md, src/maestral/sync.py, tests/linked/test_sync.py
Fixes #570. When a local moves overwrites an existing file, the existing file will now be correctly replaced on Dropbox servers. This is done by removing the remote file first, if its rev matches the local file (i.e., if it has no un-synced changes which would be lost).
=> Fix move to existing file

CHANGELOG.md, src/maestral/manager.py, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/test_main.py, tests/linked/test_sync.py
This PR fixes #555 by properly detecting when the casing of the local Dropbox directory has changed on case-insensitive file systems.
=> Handle dropbox dir case changes

src/maestral/main.py, src/maestral/notify.py
This PR replaces the usage of `asyncio.get_event_loop()` which was deprecated in Python 3.10.
=> Replace deprecated usage of `asyncio.get_event_loop()`

src/maestral/sync.py, tests/linked/conftest.py, tests/linked/test_sync.py
This PR improves some of the sync tests:
1. Tests are ordered by topic.
2. We always check that there are no fatal errors or sync errors at the end of a test (if applicable).
3. `assert_synced` provides better error messages and takes into account selective sync settings.
=> Improve tests

.github/workflows/test.yml, CHANGELOG.md, src/maestral/client.py, src/maestral/database.py, src/maestral/errors.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/conftest.py, tests/linked/test_sync.py, tests/offline/test_cleaning_events.py
This PR improves symlink handling:
1. Downloading remote symlinks is now properly supported. The symlink will be created locally instead of just a stub file.
2. Uploading local symlinks now raises a `SymlinkError` since this is not (yet) supported by the public Dropbox API.
3. Conflict resolution now takes into account symlink targets.
4. Symlink targets are stored in our index.
5. Local file system access now never follows symlinks.
=> Improve symlink handling

src/maestral/manager.py, src/maestral/utils/integration.py
1. Use Dropbox API host (https://api.dropboxapi.com) instead of website (http://www.dropbox.com) for connection check.
2. Log connection error tracebacks on the first failed attempt or when a connection is lost. See #583 why this is helpful.
=> Improve connection check

setup.cfg, src/maestral/client.py, tests/linked/test_client.py, tests/linked/test_sync.py, tests/offline/test_client.py
Simplify error handling now that errors when refreshing the access token are correctly handled by the Dropbox SDK. See https://github.com/dropbox/dropbox-sdk-python/pull/407).
=> Update authentication error handling

CHANGELOG.md, src/maestral/cli.py, src/maestral/main.py
Relative passed to `maestral move-dir` are now interpreted relative to the working directory where the command is run instead of the working directory of the sync daemon. Fixes #594.
=> Fix passing relative paths to `maestral move-dir`

src/maestral/config/__init__.py, src/maestral/config/main.py, src/maestral/config/user.py, src/maestral/database.py, src/maestral/errors.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py, src/maestral/utils/orm.py, src/maestral/utils/path.py, src/maestral/utils/serializer.py, tests/linked/conftest.py, tests/linked/test_client.py, tests/linked/test_sync.py
Migrate from lists in the state file to a single database table for upload and download errors. This significantly simplifies our error handling data structures.
=> Unified database table for sync errors

CHANGELOG.md, src/maestral/database/types.py, src/maestral/models.py
This PR fixes storage of inode numbers in our SQLite database for file systems with 64-bit inodes. This was previously a problem because inode numbers were stored as INTEGER in SQLite, supporting values `> -2**63` and `< 2**63 - 1`. However Linux supports inode numbers of unsigned 64-bit integers, going up to 2**64.
From https://www.mjr19.org.uk/sw/inodes64.html:
> Modern filesystems are starting to use 64 bit inodes, rather than 32 bit ones. Recent versions of [XFS](http://www.xfs.org/) do so for filesystems of more than 1TB, and other large filesystems such as [Lustre](http://lustre.org/) use them too. NFS fully supports them too, so one can find them when mounting remote filesystems.
Fixes #609.
=> Fix 64-bit inode handling

CHANGELOG.md, setup.cfg, src/maestral/client.py, src/maestral/errorhandling.py, src/maestral/exceptions.py, src/maestral/main.py, src/maestral/sync.py, src/maestral/utils/hashing.py, tests/linked/test_client.py, tests/offline/test_errorhandling.py
* In addition to checking offsets, also check content hashes after upload / download to prevent data corruption.
* Retry up to 3 times on data corruption. In case of chunked uploads, individual chunks will be retried up to 3 times, preserving progress from successfully uploaded data.
=> Verify file integrity after transfer

src/maestral/client.py, src/maestral/main.py
Replace `**kwargs` with explicit keyword arguments in `list_folder` and `list_folder_iterator` API endpoints of `DropboxClient` and `Maestral`.
=> Move to explicit arguments in list_folder endpoints

src/maestral/cli/cli_core.py, src/maestral/client.py, src/maestral/main.py, tests/linked/integration/test_main.py, tests/linked/unit/test_client.py
Update `DropboxClient.create_shared_link()` to replace deprecated usage of the `requested_visibility` argument with usage of the `audience` argument instead.
=> Shared link update

CHANGELOG.md, src/maestral/models.py, src/maestral/sync.py
This makes better use of multi-core CPUs for content hashing.
=> Parallelize conversion of local sync events

CHANGELOG.md, src/maestral/database/query.py
SQLite before 3.23.0 (2018-04-02) don't accept `TRUE` as a truth value, however we were using this to query all rows in a table, as defined in `maestral.database.query.AllQuery`. `TRUE` has now been replaced with `1` which is also accepted in older SQLite versions.
See https://www.sqlite.org/lang_expr.html#booleanexpr. Fixes #644.
=> Fix SQL queries for older SQLite releases

CHANGELOG.md, src/maestral/cli/cli_core.py, src/maestral/client.py
Handle cases when the Dropbox API returns `LinkPermissions.resolved_visibility` in place of `LinkPermissions.effective_audience`.
=> Improve shared link metadata conversion

CHANGELOG.md, src/maestral/client.py
This provides debugs logs for individual API calls, rate limiting, and retries on errors. All of those are performed by the Dropbox SDK and are transparent to Maestral but may still affect the user, e.g., several minute backoffs on rate limits.
=> Capture Dropbox SDK log output

CHANGELOG.md, src/maestral/config/user.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py, tests/linked/integration/test_sync.py
Persist the queue to download newly added folder in selective sync. This ensures that downloads resume properly after restarting Maestral.
=> Persist download queue

src/maestral/cli/cli_info.py, src/maestral/cli/output.py, src/maestral/client.py, src/maestral/models.py, tests/offline/test_client.py
* Convert timestamps to datetime in the output for the `history` command.
* Convert from UTC to the local timezone for all displayed time stamps.
Fixes #665.
=> Fix time stamps displayed in the CLI

src/maestral/client.py, src/maestral/fsevents/__init__.py, src/maestral/main.py, src/maestral/manager.py, tests/linked/integration/conftest.py, tests/linked/unit/conftest.py, tests/offline/conftest.py, tests/offline/test_clean_local_events.py, tests/offline/test_client.py, tests/offline/test_manager.py
Pass down dependencies to the requiring classes. This enables easier "injection" of test dependencies if required.
=> Pass down dependencies

CHANGELOG.md, src/maestral/sync.py, tests/linked/integration/test_sync.py, tests/offline/test_event_handler.py
When renaming a local item to reflect an automatic rename on upload in `SyncEngine._handle_upload_conflict()`, we discard the corresponding local file system events which gets reported.
For some versions of macOS / APFS, this does not work properly when the local item is renamed to change the unicode normalisation only. Instead of reporting the rename as it actually occurred, the new and old path are sometimes reported as being the same (and macOS APIs do in fact allow accessing the item through both paths). This would however result in spurious and incorrect file system events being reported which could lead to sync issues and loss of data.
This PR fixes this behaviour by always ignoring rename events with equal source and destination path: They are either correct, in which case there is …
=> Handle unicode renames on apfs

CHANGELOG.md, src/maestral/client.py, src/maestral/errorhandling.py, src/maestral/exceptions.py
Fixes #683 by mitigating the server-side errors with a client-side retry when refreshing the access token fails.
=> Work around failing access token refresh calls

src/maestral/cli/cli_info.py
=> Separate `maestral ls` output by new lines when not attached to terminal

CHANGELOG.md, src/maestral/client.py, src/maestral/manager.py
=> Class-level decorators are no longer static

src/maestral/client.py
Re-initialising the SDK would previously not work if we are already linked and have an initialised SDK. This regression was introduced in #619.
Fixes #713.
=> Allow relinking when the SDK has already been initialized

_docs/installation.md
Specifically mention `maestral start` as part of the installation process, as well as some everyday administration tools.
It may seem a little strange to give `docker exec -it maestral maestral status` a full mention, but I've noticed that the Maestral daemon usually starts paused, so mentioning how to run `maestral status` will make users more likely to run it immediately and notice they need to resume syncing.
This is intended to address the issues I encountered in #716.
=> Expand on Docker installation instructions

src/maestral/cli/cli_core.py, src/maestral/client.py, src/maestral/main.py, tests/linked/integration/conftest.py, tests/linked/unit/conftest.py, tests/offline/test_client.py
The regular linking flow requires going through the full OAuth flow with Maestral: 
1. Get a Dropbox URL with `Maestral.get_auth_url()`.
2. Navigating to the URL to retrieve an auth code,
3. Call `Maestral.link()` with the retrieved code to exchange it for a long-lived refresh token.
This is inconvenient for automated testing where either a long-lived refresh token or a short-lived access token are already provided, typically through environment variables.
This PR allows directly providing a refresh or access token for linking. Note that the token must be issued for Maestral, with the required scopes, and will validated during the `Maestral.link()` call.
=> Allow linking with auth tokens

src/maestral/cli/cli_info.py, src/maestral/cli/cli_maintenance.py, src/maestral/cli/common.py, src/maestral/cli/utils.py, src/maestral/manager.py, src/maestral/sync.py
* Log status while syncing immediately when there is an update. This is done by using `cuncurrent.futures.as_completed` on the futures.
* Update the activity view of `maestral activity` every 0.2 seconds.
* Limit the output of `maestral activity` to the terminal size.
=> Better status updates

setup.cfg, src/maestral/cli/cli_core.py
Fixes #767.
* The `groups` parameter to `entry_points()` is only supported from Python 3.10 and upwards in `importlib.metadata` and in `importlib_metadata` from v3.6.
* Indexed access to EntryPoints is only supported in `importlib.metadata`.
API usage is now consistent with `importlib_metadata>3.6` and we always require installing `importlib_metadata` to simplify imports and mitigate regressions.
=> Fix GUI entry-point selection for Python 3.9 and earlier

CHANGELOG.md, src/maestral/client.py, src/maestral/models.py, src/maestral/sync.py, src/maestral/utils/path.py
Fixes #779.
Note that the underlying issues was that `files/get_metadata` Dropbox API calls return metadata without symlink information when passing a revision id instead of a path as argument. Maestral would accordingly treat the remote item as a regular file. I've reported this to Dropbox.
The current workaround is to use the metadata from the `files/list_folder` call directly and handle the download in the SyncEngine instead of passing the revision id to the Client to download.
=> Fix symlink download

src/maestral/daemon.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/notify.py, src/maestral/sync.py
This makes it more explicit which event-loop is being used instead of relying on other components setting the event loop policy.
This CL also removes a two async tasks:
1. Periodic fetching of the profile picture. API clients must now do this themselves when they need it.
2. Period reindexing. This is now triggered by the download worker.
=> Pass event loop explicitly instead of creating it on-demand

src/maestral/manager.py, src/maestral/sync.py
This was previously done to work around a potential memory leak in requests which now appears fixed.
=> Don't create new client instances for each thread

CHANGELOG.md, src/maestral/cli/cli_main.py, src/maestral/cli/cli_settings.py, src/maestral/client.py, src/maestral/config/main.py, src/maestral/main.py, tests/linked/unit/test_client.py
The initial version is CLI / config file only. Bandwidth limits apply separately for uploads and downloads across all parallel transfers. Bandwidth is limited by delaying transmission of chunks at a 2 kB size, i.e., bandwidth limits < 2 kB / sec will result in spiky network usage instead of smooth limiting.
Fixes #438.
=> Allow setting bandwidth limits

.github/workflows/test.yml, CHANGELOG.md, src/maestral/client.py, src/maestral/config/main.py, src/maestral/keyring.py, tests/linked/integration/conftest.py, tests/linked/unit/conftest.py, tests/offline/test_keyring.py, tests/offline/test_manager.py
Remove support for deprecated long-lived access tokens from the keyring module. Dropbox has now fully switched to long-lived refresh tokens which can be used to fetch short-lived access tokens.
We keep the linking infrastructure in place for access tokens because those are useful for testing. However, we no longer expect them to be long-lived and therefore don't store them in the keyring anymore.
=> Remove support for long-lived access tokens in keyring module

CHANGELOG.md, src/maestral/config/main.py, src/maestral/sync.py, tests/linked/unit/test_client.py
Add new config file values `max_parallel_uploads` and `max_parallel_downloads` to control the maximum number of parallel file transfers. The default values is 6.
Config changes will only take effect after restarting Maestral.
Fixes #831.
=> Allow configuring max number of parallel transfers

CHANGELOG.md, src/maestral/client.py, src/maestral/exceptions.py, src/maestral/sync.py
If a local file is changed while being uploaded, we currently continue with the upload and proceeded to resync the file after it has completed. This has a number of disadvantages:
1. For large files, it may use unnecessary bandwidth.
2. It may result in inconsistent versions of a file being uploaded, for example if changes are made to both the byte ranges already uploaded and those pending. Even though we will eventually upload a consistent version of the file, once the user stopped editing for the duration of a single upload, this still means that a inconsistent version may be saved in Dropbox's version history.
This PR checks the file consistently for between the upload of individual chunks, by calling stat on the open file descriptor, and aborts the upload if changes are detected. …
=> Abort upload on local file changes

CHANGELOG.md, src/maestral/models.py, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/integration/test_sync.py
* Show desktop notifications when a conflicting copy is created both during upload and download sync. Unlike regular notifications, those notifications are shown for each conflicting copy instead of giving a summary count.
* Append the user name and date to a conflicting copy file name, for example `myfile (Sam's  conflicting copy 2022-08-30).pdf`.
Fixes #861.
=> Improved conflict handling

CHANGELOG.md, src/maestral/utils/integration.py
- Added error handling for systems that do not provide `/sys/class/power_supply`. Such as Synology devices.
- Fixes  #877
=> handle FileNotFoundError when determining ACState

src/maestral/utils/path.py, tests/linked/integration/test_sync.py
Currently, file or folder moves use `shutil.move()` which tries to use `os.rename()` first and will fall back to `copy2()` followed by a delete of the original item.
This has two drawbacks for moves within the Dropbox folder:
1. Some callers implicitly rely on the move to be atomic, which is only guaranteed for a rename.
2. A `copy2` may fail with different and expected error messages where the original OSError from `os.rename()` would have been handled properly. See for example #878.
This PR switches to always using `os.rename` when moving items within the local Dropbox folder.
=> Always use `os.rename` for moves

src/maestral/sync.py
This prevents us from doing some additional renaming and reindexing work where not required. This work may occasionally raise unexpected errors, see for example #878.
=> Use case-insensitive upload conflict detection on case-insensitive file systems

CHANGELOG.md, src/maestral/database/orm.py, src/maestral/models.py, src/maestral/sync.py, src/maestral/utils/__init__.py, src/maestral/utils/path.py, tests/linked/integration/test_sync.py
We currently correctly handle local case changes while Maestral is running. However, if a local item was renamed in case only while Maestral was stopped, indexing on startup won't flag the item as changed because the comparison to our index is case-insensitive. This PR fixes this issue by enforcing case-sensitive comparison.
=> Index local case changes

src/maestral/config/main.py, src/maestral/manager.py, src/maestral/utils/integration.py
Automatic reindexing every 14 days was introduced as measure to mitigate missing local file system events and potential bugs in acting on Dropbox events. Sync logic is sufficiently robust now that is no longer required.
Removing automatic reindexing will reduce the number of conflicted copies that are created by remote file edits before a file a reindexed.
See #916.
=> No automatic reindexing

CHANGELOG.md, src/maestral/autostart.py
Fixes a regression introduced in 87758efa5f154b75668325e581a3c1273a43947e which would result in malformed systemd file names. The file name should end with `@{DEFAULT_INSTANCE_NAME}.service` instead of `@%i.service`
Fixes #930.
=> Fix systemd service name

CHANGELOG.md, src/maestral/client.py, tests/linked/unit/test_client.py
Fixes an issue where data transport errors that are retried could result in zero byte files being created in the cloud if the local file size is smaller than 4 MB. This is caused but not rewinding to the beginning of the file before retrying the upload.
Note that chunked uploads for files > 4 MB are already handled correctly.
Fixes #925 and #926.
=> Fix zero byte files

CHANGELOG.md, src/maestral/cli/cli_settings.py, src/maestral/main.py, src/maestral/manager.py, src/maestral/sync.py, tests/linked/integration/test_main.py, tests/linked/integration/test_sync.py
This PR contains the following changes:
* Replace `Maestral.include_item()` and `Maestral.exclude_item()` with new APIs `Maestral.include_items()` and `Maestral.exclude_items()` that accept multiple paths.
* Update `Maestral.excluded_items` API to accept and return a set instead of a list. This better represents the semantics of excluded items, where the order is not important.
* Return a copy of excluded items from `Maestral.excluded_items` to prevent modifying the set in place. 
* Update CLI commands `excluded add` and `excluded remove` to accept multiple paths. See #958 for why this is useful.
* Split large selective sync tests into more specific test cases.
=> Allow passing multiple paths to `excluded add` and `excluded remove`

src/maestral/main.py, src/maestral/utils/path.py, tests/linked/integration/test_sync.py
If `follow_symlinks=False` is not supported for a file system call on the platform, either fall back to `follow_symlinks=True`, or skip the call if ok. In particular:
* `stat`: Use Python's `os.lstat`, which always falls back to `os.stat`. See https://docs.python.org/3/library/os.html#os.lstat.
* `chmod`: Don't call at all if `follow_symlinks=False` is not supported.
* `open`: Don't pass O_NOFOLLOW is not available.
Fixes #890.
=> be more forgiving if follow_symlinks=False is not supported

pyproject.toml, src/maestral/sync.py, src/maestral/utils/path.py, tests/linked/integration/test_sync.py, tests/offline/utils/test_path.py
Preserve both file attributes (permissions) and extended attributes (Finder tags, etc) of local files when syncing.
Note that the extended attributes will not be synced to or from the server because this is not supported by the public Dropbox API. It _is_ supported by the proprietary client, see https://help.dropbox.com/sync/extended-attributes.
Fixes #1002.
=> Preserve file metadata

src/maestral/cli/cli_settings.py, src/maestral/cli/common.py, src/maestral/main.py, src/maestral/utils/path.py, tests/offline/test_cli.py
Change CLI signature to `excluded add | remove [DROPBOX_PATHS]`, to match the implementing function's argument name.
Also add tests to prevent regressions and fix triggering fake sync events when adding excluded items on macOS.
Fixes #1030.
=> Fix `excluded add | remove` CLI argument names

tests/linked/conftest.py, tests/linked/integration/conftest.py, tests/linked/integration/test_main.py, tests/linked/integration/test_sync.py, tests/linked/lock.py, tests/linked/unit/conftest.py, tests/linked/unit/test_client.py
* Fix an issue with the test lock being deleted in cleanup before test case.
* Simplify pytest fixtures.
* Aquire lock on per-session instead of per-test-case.
* Aquire lock for a max timeout of 10 min and renew for another 10 min for each test case.
=> Test lock updates

pyproject.toml, src/maestral/models.py, src/maestral/notify.py, src/maestral/sync.py, src/maestral/utils/path.py
Update to new APIs of dependencies
=> Fix mypy issues
