samschott/maestral

CHANGELOG.md
maestral/client.py
maestral/gui/first_sync_dialog.py
maestral/main.py
requirements.txt
setup.py

Move storage of OAuth2 token from text file to system keyring for better security. Fixes #20.

keyring-storage

---

maestral/sync/client.py
maestral/sync/monitor.py

Bugfix for #50.
I needed to recreate this so that I could be working from a branch based on your `develop` branch.
Again, lmk of any other changes you'd like me to make here.

Wrap file-check with try-except (attempt 2)

---

.gitignore
maestral/resources/maestral.desktop
snap/snapcraft.yaml

This PR adds a working confined snap.
For now it needs to be connected to the kde content snap, but a request for autoconnection can be opened on the snapcraft forum.

Add snap support

---

maestral/constants.py
maestral/sync.py
maestral/utils/path.py
tests/test_sync.py
tests/utils/test_path.py

Improves the reliability and performance of case conversions in utils.path.

Path improvements

---

CHANGELOG.md
maestral/__init__.py
maestral/cli.py
maestral/config/main.py
maestral/main.py
maestral/sync.py
maestral/utils/housekeeping.py

- Introduces a command "recent-changes" to the CLI to list the last 30 file changes with time stamps.
- Add time stamps to saved file history.

CLI command "recent-changes"

---

.github/workflows/lint.yml
maestral/cli.py
maestral/client.py
maestral/config/main.py
maestral/main.py
maestral/sync.py
maestral/utils/serializer.py
tests/test_main.py
tests/test_sync.py

sync items

---

tests/test_main.py
tests/test_sync.py

This PR fixes possibly issues with test cleanup by moving all assert statements from the cleanup stage to the test functions. It also provides minor improvements to code style.

Improve test reliability

---

tests/fixtures.py
tests/test_cli.py
tests/test_main.py
tests/test_sync.py
tests/utils/test_appdirs.py
tests/utils/test_path.py
tests/utils/test_serializer.py

This PR adds a simple test of the CLI command `maestral start` and `maestral stop` as proof-of-principle. See #211 for future plans.

Cli test dummy

---

src/maestral/sync.py

* Combine for-loops where possible.
* Refactor some variables to have more meaningful names.
* Remove code which would list old revisions of a remote deletion to detect if it was a file or folder.

Indexing performance improvements

---

CHANGELOG.md
src/maestral/cli.py

This fixes #224 by retaining the Proxy connection until no longer needed.

[cli] retain proxy as long as connection is needed

---

CHANGELOG.md
docs/conf.py
setup.py
src/maestral/fsevents/fsevents.py
src/maestral/fsevents/polling.py

This works around #235 by requiring watchdog <= 0.10.3

Watchdog update

---

src/maestral/client.py
src/maestral/fsevents/fsevents.py
src/maestral/main.py
src/maestral/sync.py

See #248.
* Clear case-conversion cache and FSEventHandler ignores after sync cycle.
* Optimise some string creation.

Minor memory improvements

---

.bumpversion.cfg
CHANGELOG.md
docs/conf.py
setup.py
src/maestral/__init__.py
src/maestral/daemon.py
src/maestral/logging.py

Require maestral-qt >= v1.3.1 to fix incorrect GUI entry point.

Release v1.3.1

---

setup.py
src/maestral/utils/cli.py

This PR updates our use of survey to the new API of version 3.0.

Update to survey 3.0

---

src/maestral/sync.py
tests/offline/test_daemon.py

Reenable daemon tests on macOS.

Reenable daemon tests

---

src/maestral/cli.py
src/maestral/daemon.py
tests/linked/conftest.py
tests/offline/test_cli.py
tests/offline/test_daemon.py
tests/offline/utils/test_path.py

This PR fixes reliability issues with daemon startup on the GitHub actions test runners.

Fix daemon startup in ci

---

docs/background/log_handlers.csv
docs/background/logging.rst
setup.py
src/maestral/cli.py
src/maestral/constants.py
src/maestral/main.py

Remove bugsnag and analytics

---

src/maestral/notify/base.py
src/maestral/notify/linux.py
src/maestral/notify/macos.py
src/maestral/notify/main.py
tests/linked/conftest.py

This PR fixes a deadlock when running Maestral tests in a headless system. See #219.

Fix linux test deadlock

---

Dockerfile

Reduce the size of docker images

---

src/maestral/cli.py
src/maestral/config/main.py
src/maestral/config/user.py
src/maestral/oauth.py
tests/offline/config/test_user.py
tests/offline/test_cli.py

This PR simplifies the config modules and removes unused used.

Refactor config

---

.deepsource.toml
CHANGELOG.md
setup.py

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/maestral/issues/). This PR fixes a few of them.
- Remove reimported module
- Simplified the if statements
- Refactor the comparison involving `not`
- Added .deepsource.toml to fix bug risk
- [✔] Antipattern
- [✔] My code follows the style guidelines of this project

Fixed code quality issues

---

src/maestral/daemon.py
src/maestral/main.py
src/maestral/manager.py
src/maestral/oauth.py
src/maestral/sync.py
src/maestral/utils/__init__.py
tests/offline/conftest.py

This PR moves all manager functionality from the sync module to a new manager module.

Create new manager module

---

src/maestral/sync.py

This PR refactors the `SyncEngine.correct_case()` method:
1. Moves case conversion of dirname to helper function.
2. Improves caching when the Dropbox path neither corresponds to an existing local item or an item on Dropbox.
This provides significant performance improvements in the niche case of converting a path which is neither present in our local index or on Dropbox servers.

Refactor `correct_case`

---

src/maestral/notify.py

This PR schedules all desktop notifications as async tasks on the main thread instead of sending them synchronously from the sync threads (by temporarily spinning our own asyncio loop). This results in minor performance improvements and a cleaner implementation.

Send desktop notifications asynchronously

---

src/maestral/daemon.py
tests/offline/test_daemon.py

This PR simplifies the lock file implementation used by the daemon.

Simplify daemon lock

---

src/maestral/cli.py
tests/offline/test_cli.py

no such command `maestral cofigs`, update message to `maestral config-files`

Update command for listing configs

---

src/maestral/sync.py
src/maestral/utils/path.py

This ensures that we pass mypy type checks with the latest release.

Update path typing

---

.github/workflows/lint.yml

This unifies what is run locally and on CI.

Run linters from pre-commit

---

.github/dependabot.yml

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Configure github-actions in dependabot

---

tests/offline/utils/test_path.py

Fixes #562 by ensuring that the test path always exists when required.

Aways use temporary path for `.utils.path` tests

---

CHANGELOG.md
src/maestral/database.py
src/maestral/main.py
src/maestral/manager.py
src/maestral/sync.py
src/maestral/utils/orm.py
tests/linked/test_sync.py

* Simplify code to update or create database entries.
* Unify duplicate code to handle upload sync conflicts.
* Improve sync error handling and clearing.

Code cleanup

---

Dockerfile

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Bump Python to 3.10 in Dockerfile

---

.pre-commit-config.yaml
setup.cfg
src/maestral/autostart.py
src/maestral/cli/cli_core.py
src/maestral/cli/cli_maintenance.py
src/maestral/cli/common.py
src/maestral/cli/core.py
src/maestral/cli/dialogs.py
src/maestral/cli/output.py
src/maestral/client.py
src/maestral/config/main.py
src/maestral/config/user.py
src/maestral/daemon.py
src/maestral/database/orm.py
src/maestral/database/query.py
src/maestral/database/types.py
src/maestral/errorhandling.py
src/maestral/exceptions.py
src/maestral/logging.py
src/maestral/main.py
src/maestral/manager.py
src/maestral/models.py
src/maestral/notify.py
src/maestral/oauth.py
src/maestral/sync.py
src/maestral/utils/serializer.py

* Drop support for Python 3.6
* Switch to modern type annotations with postponed evaluation.

Modernise type annotations

---

tests/linked/test_main.py
tests/offline/conftest.py
tests/offline/test_main.py
tests/offline/test_manager.py

Using mocking to simplify test setup.

Test improvements

---

src/maestral/main.py
src/maestral/oauth.py
tests/linked/conftest.py
tests/linked/test_main.py
tests/offline/conftest.py
tests/offline/test_main.py
tests/offline/test_manager.py
tests/offline/test_oauth.py

Move all tricky state handling to internal APIs.

OAuth improvements

---

src/maestral/client.py
src/maestral/errorhandling.py

* Use `@retry_on_error decorator` for list folder logic.
* Move max retry constants to class variables.

List folder retries

---

CHANGELOG.md
src/maestral/client.py
src/maestral/core.py
tests/offline/test_client.py

Fixes #643 and adds missing tests.

Fix space usage conversion

---

tests/offline/utils/test_path.py

Adapt path tests to changes introduced in 135fef34f3c0937a1e0f6f52070c56f45642467d.

Updated path tests

---

setup.cfg
src/maestral/cli/cli_core.py
src/maestral/cli/cli_info.py
src/maestral/cli/cli_maintenance.py
src/maestral/cli/output.py
src/maestral/cli/utils.py

This allows us to show nice progress bars for uploads and downloads. It also removes a dependency on ncurses, which was causing long-standing issues for macOS packaging (fixes #699).
The look of the new activity screen:

Switch from ncurses to rich for live activity view

---

src/maestral/autostart.py
src/maestral/utils/integration.py

Look at the contents of `/proc/1/comm` to detect the init system used on Linux instead of relying on `ps -p 1` because `ps` might not be available or the `-p` flag may not be supported. Fixes #839.

Cross-distro init system detection

---

CHANGELOG.md
src/maestral/client.py
src/maestral/main.py
src/maestral/utils/path.py

Support systems where chmod and utime don't have follow_symlinks option

---

src/maestral/sync.py

Use a dictionary to track linked events instead. This is safer since it does not meddle with classes that we don't own.

[sync] don't patch file events to track moves

---

CHANGELOG.md
src/maestral/main.py
src/maestral/sync.py
tests/linked/integration/test_main.py

Perform case-sensitive `filestatus` checks on case-sensitive file systems

---

src/maestral/database/orm.py
src/maestral/sync.py

Automatically attempt recreate the DB and reindex on corruption.

Recreate database on corruption

---

src/maestral/client.py
tests/linked/integration/test_sync.py

Fix mtime syncing
